export const GET_EXHIBITION_LIST_REQUEST = "GET_EXHIBITION_LIST_REQUEST";
export const GET_EXHIBITION_LIST_SUCCESS = "GET_EXHIBITION_LIST_SUCCESS";
export const GET_EXHIBITION_LIST_FAILURE = "GET_EXHIBITION_LIST_FAILURE";
