export const GET_EXHIBITION_LIST_REQUEST = 'GET_EXHIBITION_LIST_REQUEST';
export const GET_EXHIBITION_LIST_SUCCESS = 'GET_EXHIBITION_LIST_SUCCESS';
export const GET_EXHIBITION_LIST_FAILURE = 'GET_EXHIBITION_LIST_FAILURE';

export const GET_UPCOMING_EXHIBITION_LIST_REQUEST =
  'GET_UPCOMING_EXHIBITION_LIST_REQUEST';
export const GET_UPCOMING_EXHIBITION_LIST_SUCCESS =
  'GET_UPCOMING_EXHIBITION_LIST_SUCCESS';
export const GET_UPCOMING_EXHIBITION_LIST_FAILURE =
  'GET_UPCOMING_EXHIBITION_LIST_FAILURE';

export const GET_TRENDING_EXHIBITION_LIST_REQUEST =
  'GET_TRENDING_EXHIBITION_LIST_REQUEST';
export const GET_TRENDING_EXHIBITION_LIST_SUCCESS =
  'GET_TRENDING_EXHIBITION_LIST_SUCCESS';
export const GET_TRENDING_EXHIBITION_LIST_FAILURE =
  'GET_TRENDING_EXHIBITION_LIST_FAILURE';
