export const POST_ADD_TO_WISHLIST_REQUEST = 'POST_ADD_TO_WISHLIST_REQUEST';
export const POST_ADD_TO_WISHLIST_SUCCESS = 'POST_ADD_TO_WISHLIST_SUCCESS';
export const POST_ADD_TO_WISHLIST_FAILURE = 'POST_ADD_TO_WISHLIST_FAILURE';
