export const POST_ADD_TO_WISHLIST_REQUEST = 'POST_ADD_TO_WISHLIST_REQUEST';
export const POST_ADD_TO_WISHLIST_SUCCESS = 'POST_ADD_TO_WISHLIST_SUCCESS';
export const POST_ADD_TO_WISHLIST_FAILURE = 'POST_ADD_TO_WISHLIST_FAILURE';

export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE';

export const GET_REMOVE_FROM_WISHLIST_REQUEST = 'GET_REMOVE_FROM_WISHLIST_REQUEST';
export const GET_REMOVE_FROM_WISHLIST_SUCCESS = 'GET_REMOVE_FROM_WISHLIST_SUCCESS';
export const GET_REMOVE_FROM_WISHLIST_FAILURE = 'GET_REMOVE_FROM_WISHLIST_FAILURE';
