export const CHECKOUT_BAG_REQUEST = 'CHECKOUT_BAG_REQUEST';
export const CHECKOUT_BAG_SUCCESS = 'CHECKOUT_BAG_SUCCESS';
export const CHECKOUT_BAG_FAILURE = 'CHECKOUT_BAG_FAILURE';

export const SELECT_ADDRESS_REQUEST = 'SELECT_ADDRESS_REQUEST';
export const SELECT_ADDRESS_SUCCESS = 'SELECT_ADDRESS_SUCCESS';
export const SELECT_ADDRESS_FAILURE = 'SELECT_ADDRESS_FAILURE';

export const SELECT_PAYMENT_METHOD_REQUEST = 'SELECT_PAYMENT_METHOD_REQUEST';
export const SELECT_PAYMENT_METHOD_SUCCESS = 'SELECT_PAYMENT_METHOD_SUCCESS';
export const SELECT_PAYMENT_METHOD_FAILURE = 'SELECT_PAYMENT_METHOD_FAILURE';

export const SELECT_SHIPPING_METHOD_REQUEST = 'SELECT_PAYMENT_METHOD_REQUEST';
export const SELECT_SHIPPING_METHOD_SUCCESS = 'SELECT_PAYMENT_METHOD_SUCCESS';
export const SELECT_SHIPPING_METHOD_FAILURE = 'SELECT_PAYMENT_METHOD_FAILURE';

export const SELECT_DELIVERY_ADDRESS = 'SELECT_DELIVERY_ADDRESS';
export const SELECT_SHIPPING_METHOD = 'SELECT_SHIPPING_METHOD';
export const SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD';
