export const ADD_TO_BAG_REQUEST = "ADD_TO_BAG_REQUEST";
export const ADD_TO_BAG_SUCCESS = "ADD_TO_BAG_SUCCESS";
export const ADD_TO_BAG_FAILURE = "ADD_TO_BAG_FAILURE";

export const REMOVE_FROM_BAG_REQUEST = "REMOVE_FROM_BAG_REQUEST";
export const REMOVE_FROM_BAG_SUCCESS = "REMOVE_FROM_BAG_SUCCESS";
export const REMOVE_FROM_BAG_FAILURE = "REMOVE_FROM_BAG_FAILURE";

export const GET_BAG_REQUEST = "GET_BAG_REQUEST";
export const GET_BAG_SUCCESS = "GET_BAG_SUCCESS";
export const GET_BAG_FAILURE = "GET_BAG_FAILURE";
