export const GET_ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const GET_ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE';

export const GET_ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE';
