export const GET_PROFILE_DETAILS_REQUEST = 'GET_PROFILE_DETAILS_REQUEST';
export const GET_PROFILE_DETAILS_SUCCESS = 'GET_PROFILE_DETAILS_SUCCESS';
export const GET_PROFILE_DETAILS_FAILURE = 'GET_PROFILE_DETAILS_FAILURE';

export const EDIT_PROFILE_DETAILS_REQUEST = 'EDIT_PROFILE_DETAILS_REQUEST';
export const EDIT_PROFILE_DETAILS_SUCCESS = 'EDIT_PROFILE_DETAILS_SUCCESS';
export const EDIT_PROFILE_DETAILS_FAILURE = 'EDIT_PROFILE_DETAILS_FAILURE';
