export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE";

export const ADD_FILTERS = 'ADD_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const SET_FILTERS = 'SET_FILTERS';
