export const GET_ADDRESS_LIST_REQUEST = "GET_ADDRESS_LIST_REQUEST";
export const GET_ADDRESS_LIST_SUCCESS = "GET_ADDRESS_LIST_SUCCESS";
export const GET_ADDRESS_LIST_FAILURE = "GET_ADDRESS_LIST_FAILURE";
